# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class S3reverse < Formula
  desc "The format of various s3 buckets is convert in one format. for bugbounty and security testing."
  homepage "https://www.hahwul.com"
  version "1.0.1"
  bottle :unneeded

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/hahwul/dalfox/releases/download/v1.0.1/s3reverse_1.0.1_darwin_amd64.tar.gz"
      sha256 "644ec0e6fd22d6bfda6068f64f783cfe399eb06d2f07c6d7522d29497b2f0484"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/hahwul/dalfox/releases/download/v1.0.1/s3reverse_1.0.1_linux_amd64.tar.gz"
      sha256 "470bd8f7b1a3cbf6596b1cd66b1464170603479895d71c6a2b69f87581f992a3"
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/hahwul/dalfox/releases/download/v1.0.1/s3reverse_1.0.1_linux_armv6.tar.gz"
      sha256 "032ad4318c31b67a28b18c784b4bed6415e6f81adaa34d9a12453b05fb9a4479"
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/hahwul/dalfox/releases/download/v1.0.1/s3reverse_1.0.1_linux_arm64.tar.gz"
      sha256 "498d4b8904cad3726d6e7edf6ab52a82c539e658264a104cb6a5905b06951eb1"
    end
  end

  def install
    bin.install "s3reverse"
  end

  test do
    system "#{bin}/s3reverse"
  end
end
