# This file was generated by GoReleaser. DO NOT EDIT.
class S3reverse < Formula
  desc "The format of various s3 buckets is convert in one format. for bugbounty and security testing."
  homepage "https://www.hahwul.com"
  version "1.0.0"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/hahwul/dalfox/releases/download/v1.0.0/s3reverse_1.0.0_darwin_amd64.tar.gz"
    sha256 "536759770745df9853edc9b5075c431424e93bbf330144ac34fcd834dad8fb6a"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/hahwul/dalfox/releases/download/v1.0.0/s3reverse_1.0.0_linux_amd64.tar.gz"
      sha256 "8e67ef489f70094085bfd61608a1e72ffabe61dd262e3784d322639865401ec2"
    end
  end

  def install
    bin.install "s3reverse"
  end

  test do
    system "#{bin}/s3reverse"
  end
end
